import os

SECRET_KEY = os.getenv("JWT_SECRET_KEY")
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 60
GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")
COOKIE_NAME = "access_token"

OLLAMA_URL = os.getenv("OLLAMA_BASE_URL")
DATABASE_URL = os.getenv("DATABASE_URL")